### ISSUE TITLE
A given achievement starts rendering only when half of it will be visible at the bottom of the container

### ISSUE THREAD

**Issue by xparadoxical** [LimeGradient/BetterAchievements#3]
![GeometryDash_wHTfvlGEo6](https://github.com/user-attachments/assets/66e68f8b-424f-40e1-b144-61e868b2c902)

This is noticable also when scrolling fast.

**Comment by LimeGradient** [comment]
-

**Comment by xparadoxical** [comment]
now it's much more than half
![GeometryDash_N80N57UVme](https://github.com/user-attachments/assets/60bc0225-a49e-4e4d-b15b-af12d0a9570c)
